name: ci

on:
  push:
    branches:
      - master
  # schedule:
     # - cron: "0 8 * * *"

# jobs:
#   autogreen:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clone repository
#         uses: actions/checkout@v2

#       - name: fentouu
#         run: |
#           git config --local user.email "1832004940@qq.com"
#           git config --local user.name "wsmnnmm"
#           git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#           git pull --rebase
#           git commit --allow-empty -m "a commit a day keeps your girlfriend away"
#           git push
